#!/usr/bin/env bash
# okey
HOSTS_FILE="/etc/hosts"
NEW_LOCALHOST_IP="127.0.0.2"
NEW_FACEBOOK_IP="8.8.8.8"
FACEBOOK_DOMAIN="facebook.com"

sudo sed -i.bak -e "/^127\.0\.0\.1/c\\${NEW_LOCALHOST_IP} localhost" \
                -e "/${FACEBOOK_DOMAIN}/d" \
                "$HOSTS_FILE"
